services:
  superar1_iststicket:
    build: .

    container_name: superar1_iststicket

    restart: unless-stopped

    environment:
      TZ: America/Guayaquil

    ports:
      - "8086:80"

    env_file:
      - .env

    volumes:
      - ./storage:/var/www/html/storage
      - ./public/cci-attachments:/var/www/html/public/cci-attachments
      - ./timezone.ini:/usr/local/etc/php/conf.d/99-timezone.ini:ro

    networks:
      - moodle_net

networks:
  moodle_net:
    external: true
